version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: terraform
    directory: envs/*
    schedule:
      interval: daily

- package-ecosystem: terraform
    directory: envs/production
    schedule:
      interval: daily

- package-ecosystem: terraform
    directory: envs/staging
    schedule:
      interval: daily

- package-ecosystem: terraform
    directory: envs/master
    schedule:
      interval: daily
