name: Terraform Runner

on:
  push:
    branches:
      - main
  pull_request:

  # For terraform apply
  push:
    branches: [main]

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    secrets:
      env: |
        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
    