name: Terraform Runner

on:
  # For terraform plan
  pull_request:
    types: [labeled, opened, reopened, synchronize]

  # For terraform apply
  push:
    branches: [main]

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    env:
      TF_VAR_region: us-east-1
