name: Terraform Runner

on:
  # For terraform plan
  pull_request:
    types: [labeled, opened, reopened, synchronize]

  # For terraform apply
  push:
    branches: [main]

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    permissions:
      pull-requests: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github
      - run: aws sts get-caller-identity