name: Terraform Runner

on:
  # For terraform plan
  pull_request:
    types: [labeled, opened, reopened, synchronize]

  # For terraform apply
  push:
    branches: [main]

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    secrets: 
      env: |
        AWS_DEFAULT_REGION: us-east-1